"""Tests for plugins/slate/assets/board/board.py (Contract 1 + Contract 2 of the v0.1 plan)."""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict

import pytest

from conftest import (BOARD_SRC, FIXTURES, FORGE_BOARD, USER_TEST, Board, base_doc,
                      full_ticket)


def errors_of(board: Board) -> str:
    r = board.run("check")
    return r.stderr


def check_json(board: Board) -> Dict[str, Any]:
    r = board.run("check", "--json")
    return json.loads(r.stdout)


def assert_error(board: Board, doc: Dict[str, Any], *fragments: str) -> None:
    board.write(doc)
    r = board.run("check")
    assert r.returncode == 1, r.stdout + r.stderr
    for f in fragments:
        assert f in r.stderr, f"{f!r} not in:\n{r.stderr}"


# --------------------------------------------------------------------------- header / init


def test_header_lines_exact() -> None:
    lines = BOARD_SRC.read_text(encoding="utf-8").splitlines()[:4]
    assert lines == [
        "#!/usr/bin/env python3",
        "# Slate board v0.2.0 — generated by the Slate plugin; do not edit, run /slate:upgrade",
        'SLATE_VERSION = "0.2.0"',
        "SCHEMA_VERSION = 2",
    ]


def test_init_creates_board(board: Board) -> None:
    board.ok("init", "--project", "Acme", "--prefix", "ACME", "--areas", "api,web,ui")
    doc = board.load()
    assert list(doc) == ["meta", "phases", "tickets"]
    m = doc["meta"]
    assert m["project"] == "Acme" and m["prefix"] == "ACME"
    assert m["slate_version"] == "0.2.0" and m["schema_version"] == 2  # v0.2: schema 2, merge_ready
    assert m["statuses"] == ["draft", "backlog", "ready", "in_progress", "review", "user_testing",
                             "merge_ready", "done"]
    assert m["areas"] == ["api", "web", "ui"]
    assert m["priorities"] == ["P0", "P1", "P2", "P3"]
    assert m["user_test_areas"] == ["frontend", "ui"]
    assert doc["phases"] == [] and doc["tickets"] == []
    board.ok("check")


def test_init_default_areas_and_refuses_existing(board: Board) -> None:
    board.ok("init", "--project", "Acme", "--prefix", "ACME")
    assert board.load()["meta"]["areas"] == ["backend", "frontend", "infra"]
    r = board.fail("init", "--project", "Acme", "--prefix", "ACME")
    assert "already exists" in r.stderr


@pytest.mark.parametrize("prefix", ["acme", "A", "1ACME", "ACME-X", "ABCDEFGHIJK"])
def test_init_bad_prefix(board: Board, prefix: str) -> None:
    r = board.fail("init", "--project", "Acme", "--prefix", prefix)
    assert "prefix" in r.stderr
    assert not board.tickets.exists()


def test_usage_error_exit_2(board: Board) -> None:
    board.fail("init", "--project", "Acme", code=2)
    board.fail("bogus-command", code=2)


def test_runs_from_repo_root_and_from_kanban(seeded: Board) -> None:
    a = seeded.ok("list", cwd=seeded.root).stdout
    b = seeded.ok("list", cwd=seeded.dir).stdout
    elsewhere = seeded.root / "some" / "where"
    elsewhere.mkdir(parents=True)
    c = seeded.ok("list", cwd=elsewhere).stdout
    assert a == b == c and "ACME-001" in a


# --------------------------------------------------------------------------- version


def fake_plugin(root: Path, version: str) -> Path:
    p = root / f"plugin-{version}"
    (p / ".claude-plugin").mkdir(parents=True)
    (p / ".claude-plugin" / "plugin.json").write_text(json.dumps({"name": "slate", "version": version}))
    return p


def test_version_plain_and_json(seeded: Board) -> None:
    # seeded is a v1 board (0.1.0 / schema 1) read by the v0.2 board.py
    out = seeded.ok("version").stdout.strip()
    assert out == "board 0.2.0 · schema 2 · tickets.json 0.1.0/1"
    j = json.loads(seeded.ok("version", "--json").stdout)
    assert j == {"board": "0.2.0", "schema": 2, "file_slate_version": "0.1.0", "file_schema_version": 1,
                 "plugin": None, "relation": None}


@pytest.mark.parametrize("plugin,relation", [("0.3.0", "behind"), ("0.2.0", "same"), ("0.1.0", "ahead")])
def test_version_against(seeded: Board, plugin: str, relation: str) -> None:
    seeded.ok("migrate")  # bring the v1 fixture to 0.2.0 / schema 2 so "same" is possible
    root = fake_plugin(seeded.root, plugin)
    out = seeded.ok("version", "--against", str(root)).stdout.strip()
    assert out.endswith(f"plugin {plugin} · {relation}")
    j = json.loads(seeded.ok("version", "--against", str(root), "--json").stdout)
    assert j["plugin"] == plugin and j["relation"] == relation


def test_version_behind_when_file_older(seeded: Board) -> None:
    doc = seeded.load()
    doc["meta"]["slate_version"] = "0.0.5"
    seeded.write(doc)
    root = fake_plugin(seeded.root, "0.2.0")
    j = json.loads(seeded.ok("version", "--against", str(root), "--json").stdout)
    assert j["relation"] == "behind" and j["file_slate_version"] == "0.0.5"


def test_version_missing_tickets(board: Board) -> None:
    assert "tickets.json missing" in board.ok("version").stdout


def test_version_against_bad_plugin_root(seeded: Board) -> None:
    r = seeded.fail("version", "--against", str(seeded.root / "nope"))
    assert "plugin.json" in r.stderr


# --------------------------------------------------------------------------- next / list / status / show


def test_next_missing_tickets_prints_nothing(board: Board) -> None:
    for args in (("next",), ("next", "--brief"), ("next", "--json")):
        r = board.ok(*args)
        assert r.stdout == "" and r.stderr == ""


def test_next_picks_lowest_rank_ready(seeded: Board) -> None:
    out = seeded.ok("next").stdout
    assert "Next ticket:" in out and "ACME-001" in out.split("Next ticket:")[1]
    j = json.loads(seeded.ok("next", "--json").stdout)
    assert j["next"]["id"] == "ACME-001" and j["open"] == [] and j["user_testing"] == []


def test_next_open_first_and_brief(seeded: Board) -> None:
    doc = seeded.load()
    doc["tickets"][0]["status"] = "done"
    doc["tickets"][1]["status"] = "review"
    doc["tickets"].append(full_ticket(4, areas=["frontend"], user_tests=[USER_TEST], status="user_testing"))
    doc["tickets"].append(full_ticket(5, areas=["frontend"], user_tests=[USER_TEST], status="user_testing"))
    seeded.write(doc)
    out = seeded.ok("next").stdout
    assert out.index("Resume first") < out.index("Next ticket")
    assert "Waiting for you to test" in out
    brief = seeded.ok("next", "--brief").stdout.strip()
    assert brief == "Slate 0.2.0: ACME-002 in review · 2 waiting for you to test · next ready ACME-003"
    behind = fake_plugin(seeded.root, "0.3.0")
    brief = seeded.ok("next", "--brief", "--against", str(behind)).stdout.strip()
    assert brief.endswith(" · board behind plugin, run /slate:upgrade")
    same = fake_plugin(seeded.root, "0.2.0")
    # the v1 file itself is behind a 0.2.0 plugin until migrated
    assert "behind" in seeded.ok("next", "--brief", "--against", str(same)).stdout
    seeded.ok("migrate")
    assert "behind" not in seeded.ok("next", "--brief", "--against", str(same)).stdout


def test_next_and_list_skip_drafts(seeded: Board) -> None:
    doc = seeded.load()
    for t in doc["tickets"]:
        t["rank"] += 1
    doc["tickets"].insert(0, {"id": "ACME-004", "title": "Idea", "summary": "Maybe", "phase": "P1",
                              "rank": 1, "status": "draft"})  # lowest rank, but a draft
    seeded.write(doc)
    seeded.ok("check")
    assert "ACME-004" not in seeded.ok("next").stdout
    ids = [t["id"] for t in json.loads(seeded.ok("list", "--json").stdout)]
    assert "ACME-004" not in ids and ids[0] == "ACME-001"


def test_list_n_and_json(seeded: Board) -> None:
    out = seeded.ok("list").stdout.strip().splitlines()
    assert [re.search(r"ACME-\d+", l).group(0) for l in out] == ["ACME-001", "ACME-003"]  # 002 waits on 001
    assert len(seeded.ok("list", "1").stdout.strip().splitlines()) == 1
    j = json.loads(seeded.ok("list", "5", "--json").stdout)
    assert [t["id"] for t in j] == ["ACME-001", "ACME-003"]


def test_status_plain_and_json(seeded: Board) -> None:
    doc = seeded.load()
    doc["tickets"][0]["status"] = "done"
    doc["tickets"].append(full_ticket(4, areas=["frontend"], user_tests=[USER_TEST], status="user_testing",
                                      title="Reset page"))
    seeded.write(doc)
    out = seeded.ok("status").stdout
    assert "P1 Link arrives" in out and "1/4" in out
    assert "Waiting for you to test" in out and "ACME-004  Reset page" in out
    j = json.loads(seeded.ok("status", "--json").stdout)
    assert j["phases"][0] == {"id": "P1", "name": "Link arrives", "total": 4, "done": 1, "in_flight": 1}
    assert j["counts"]["backlog"] == 2 and j["counts"]["draft"] == 0
    assert [t["id"] for t in j["user_testing"]] == ["ACME-004"]


def rich_ticket() -> Dict[str, Any]:
    return full_ticket(
        4,
        title="People can reset a forgotten password",
        summary="Someone who forgot their password can get back in with an email link. " * 3,
        story="Priya forgets her password and clicks 'Forgot password'.",
        visual="```\nUser ──▶ App ──▶ Email\n```",
        description="What is in:\n\n- a form\n- an email\n\n| a | b |\n|---|---|\n| 1 | 2 |",
        acceptance=["A reset email arrives", "The link works once"],
        test_scenarios=["When a known email is submitted, then one email is queued"],
        user_tests=[USER_TEST, dict(USER_TEST, title="Unknown email", required=False)],
        user_checks={"0": {"result": "pass", "date": "2026-09-26", "note": "looked fine"}},
        technical="Route POST /reset.",
        plan_doc="docs/plans/2026-09-26-reset.md",
        areas=["frontend"],
        depends_on=["ACME-001"],
        handoff=[{"date": "2026-09-26", "status": "review", "note": "Built the form."}],
    )


def test_show_plain_sections_in_drawer_order(seeded: Board) -> None:
    doc = seeded.load()
    doc["tickets"].append(rich_ticket())
    seeded.write(doc)
    seeded.ok("check")
    out = seeded.ok("show", "ACME-004").stdout
    order = ["Summary", "Story", "Picture", "Done when", "Try it yourself", "Automated tests", "Details",
             "Technical notes", "Needs / unlocks", "Plan doc", "History"]
    pos = [out.index("\n" + h + "\n") for h in order]
    assert pos == sorted(pos), out
    assert out.startswith("ACME-004 · People can reset a forgotten password\n")
    assert "Phase P1 (Link arrives)" in out
    assert "      1. Click 'Forgot password'" in out and "      3. Click 'Send link'" in out
    assert "Test 1 (required): Reset with a known email" in out
    assert "Result: pass on 2026-09-26 (looked fine)" in out
    assert "Test 2 (optional): Unknown email" in out and "Result: not tried yet" in out
    assert "  ```\n  User ──▶ App ──▶ Email\n  ```" in out
    assert "Needs: ACME-001 (backlog)" in out
    assert "docs/plans/2026-09-26-reset.md" in out
    assert "2026-09-26 · review: Built the form." in out
    assert all(len(l) <= 80 for l in out.splitlines() if "──" not in l), out
    j = json.loads(seeded.ok("show", "ACME-004", "--json").stdout)
    assert j["id"] == "ACME-004" and j["user_checks"]["0"]["result"] == "pass"


def test_show_legacy_description_first(board: Board) -> None:
    shutil.copy(FIXTURES / "legacy-forge-mini.json", board.tickets)
    out = board.ok("show", "FORGE-002").stdout
    assert out.index("Details") < out.index("Done when")
    assert "Summary" not in out


def test_show_unknown_id(seeded: Board) -> None:
    r = seeded.fail("show", "ACME-999")
    assert "ACME-999" in r.stderr


# --------------------------------------------------------------------------- check: every rule


def test_check_ok_and_json(seeded: Board) -> None:
    assert seeded.ok("check").stdout.startswith("ok:")
    j = check_json(seeded)
    assert j["ok"] is True and j["errors"] == []


def test_check_invalid_json(board: Board) -> None:
    board.tickets.write_text("{ not json", encoding="utf-8")
    r = board.fail("check")
    assert "not valid JSON" in r.stderr


@pytest.mark.parametrize("field", ["project", "prefix", "statuses"])
def test_rule_meta_required(board: Board, field: str) -> None:
    doc = base_doc([full_ticket(1)])
    del doc["meta"][field]
    assert_error(board, doc, f"meta {field}: missing")


def test_rule_ids_unique(board: Board) -> None:
    assert_error(board, base_doc([full_ticket(1), full_ticket(1, rank=2)]), "ACME-001 id: duplicate")


def test_rule_id_format(board: Board) -> None:
    assert_error(board, base_doc([full_ticket(1, id="ACME-1")]), "ACME-1 id: must look like ACME-001")


def test_rule_dep_exists(board: Board) -> None:
    assert_error(board, base_doc([full_ticket(1, depends_on=["ACME-042"])]),
                 "ACME-001 depends_on: 'ACME-042' does not exist")


def test_rule_no_cycles(board: Board) -> None:
    doc = base_doc([full_ticket(1, depends_on=["ACME-002"]), full_ticket(2, depends_on=["ACME-001"])])
    assert_error(board, doc, "dependency cycle")


def test_rule_ranks_unique(board: Board) -> None:
    assert_error(board, base_doc([full_ticket(1), full_ticket(2, rank=1)]), "rank: 1 is also used by ACME-001")


def test_rule_rank_after_deps(board: Board) -> None:
    doc = base_doc([full_ticket(1, rank=5), full_ticket(2, rank=3, depends_on=["ACME-001"])])
    assert_error(board, doc, "ACME-002 rank: 3 must come after dependency ACME-001")


def test_rule_phase_exists(board: Board) -> None:
    assert_error(board, base_doc([full_ticket(1, phase="P9")]), "ACME-001 phase: 'P9' is not a phase")


def test_rule_status_known(board: Board) -> None:
    assert_error(board, base_doc([full_ticket(1, status="doing")]), "ACME-001 status: 'doing' is not one of")


@pytest.mark.parametrize("field", ["title", "phase", "priority", "rank", "status", "depends_on", "areas",
                                   "estimate", "summary", "story", "description", "acceptance",
                                   "test_scenarios"])
def test_rule_required_fields(board: Board, field: str) -> None:
    t = full_ticket(1)
    del t[field]
    assert_error(board, base_doc([t]), f"ACME-001 {field}: missing")


def test_rule_empty_acceptance_is_missing(board: Board) -> None:
    assert_error(board, base_doc([full_ticket(1, acceptance=[])]), "ACME-001 acceptance: missing")


def test_rule_done_needs_deps_done(board: Board) -> None:
    doc = base_doc([full_ticket(1), full_ticket(2, depends_on=["ACME-001"], status="done")])
    assert_error(board, doc, "ACME-002 status: done, but dependency ACME-001 is backlog")


def test_rule_done_needs_required_user_test_pass(board: Board) -> None:
    doc = base_doc([full_ticket(1, areas=["frontend"], user_tests=[USER_TEST], status="done")])
    assert_error(board, doc, "ACME-001 user_checks: done, but required user test 0")
    doc["tickets"][0]["user_checks"] = {"0": {"result": "pass", "date": "2026-09-26", "note": ""}}
    board.write(doc)
    board.ok("check")


def test_rule_user_test_areas(board: Board) -> None:
    assert_error(board, base_doc([full_ticket(1, areas=["frontend"])]),
                 "ACME-001 user_tests: area 'frontend' is in meta.user_test_areas")
    optional_only = dict(USER_TEST, required=False)
    assert_error(board, base_doc([full_ticket(1, areas=["ui"], user_tests=[optional_only])]),
                 "ACME-001 user_tests")


def test_rule_user_test_shape(board: Board) -> None:
    bad = {"title": "x", "steps": [], "expect": ""}
    assert_error(board, base_doc([full_ticket(1, user_tests=[bad])]),
                 "ACME-001 user_tests[0].steps", "ACME-001 user_tests[0].expect")


def test_rule_user_checks_index(board: Board) -> None:
    t = full_ticket(1, user_tests=[USER_TEST], user_checks={"3": {"result": "pass"}})
    assert_error(board, base_doc([t]), "ACME-001 user_checks[3]: no user test at that index")


def test_rule_non_draft_depends_on_draft(board: Board) -> None:
    draft = {"id": "ACME-001", "title": "Idea", "summary": "s", "phase": "P1", "rank": 1, "status": "draft"}
    assert_error(board, base_doc([draft, full_ticket(2, depends_on=["ACME-001"])]),
                 "ACME-002 depends_on: ACME-001 is a draft")


def test_rule_draft_relaxed_but_needs_title_summary_phase(board: Board) -> None:
    draft = {"id": "ACME-001", "title": "Idea", "summary": "s", "phase": "P1", "rank": 1, "status": "draft",
             "areas": ["frontend"]}
    other_draft = {"id": "ACME-002", "title": "Idea 2", "summary": "s", "phase": "P1", "rank": 2,
                   "status": "draft", "depends_on": ["ACME-001"]}
    board.write(base_doc([draft, other_draft]))
    board.ok("check")  # no story/description/user tests needed; drafts may depend on drafts
    d2 = dict(draft)
    del d2["summary"]
    assert_error(board, base_doc([d2]), "ACME-001 summary: missing (required, even for a draft)")


def test_warnings_do_not_fail(board: Board) -> None:
    t = full_ticket(1, title="x" * 90, test_scenarios=["It works"])
    del t["technical"]
    board.write(base_doc([t]))
    r = board.ok("check")
    assert "warning: ACME-001 title: is 90 characters" in r.stdout
    assert "warning: ACME-001 test_scenarios" in r.stdout
    assert "warning: ACME-001 technical: missing" in r.stdout
    j = check_json(board)
    assert j["ok"] and {w["field"] for w in j["warnings"]} >= {"title", "test_scenarios", "technical"}


def test_warning_visual_for_multistep_flow(board: Board) -> None:
    board.write(base_doc([full_ticket(1, areas=["frontend"], user_tests=[USER_TEST])]))
    assert "warning: ACME-001 visual" in board.ok("check").stdout


def test_legacy_ticket_warnings_not_errors(board: Board) -> None:
    shutil.copy(FIXTURES / "legacy-forge-mini.json", board.tickets)
    doc = board.load()
    doc["meta"]["prefix"] = "FORGE"
    board.write(doc)
    r = board.ok("check")
    assert "warning: FORGE-001 summary, story: missing" in r.stdout
    assert "warning: FORGE-002 user_tests" in r.stdout  # frontend legacy ticket -> warning only
    assert "warning: meta schema_version" in r.stdout


def test_check_error_names_ticket_and_field_on_stderr(board: Board) -> None:
    t = full_ticket(1)
    del t["story"]
    board.write(base_doc([t]))
    r = board.fail("check")
    assert "error: ACME-001 story: missing (required)" in r.stderr
    j = check_json(board)
    assert j["ok"] is False and {"id": "ACME-001", "field": "story", "message": "missing (required)"} in [
        {k: e[k] for k in ("id", "field", "message")} for e in j["errors"]]
    assert all(e["fix"] for e in j["errors"])


# --------------------------------------------------------------------------- write guards


def test_writes_refuse_when_board_invalid(seeded: Board) -> None:
    doc = seeded.load()
    del doc["tickets"][0]["story"]
    seeded.write(doc)
    before = seeded.tickets.read_bytes()
    for args in (("set", "ACME-003", "in_progress"), ("edit", "ACME-003", "title=New"),
                 ("add-phase", "--id", "P9", "--name", "n", "--goal", "g", "--demo", "d"),
                 ("rerank", "ACME-003", "--first")):
        r = seeded.fail(*args)
        assert "has errors" in r.stderr and "ACME-001 story" in r.stderr
    assert seeded.tickets.read_bytes() == before


def test_writes_refuse_when_schema_newer(seeded: Board) -> None:
    doc = seeded.load()
    doc["meta"]["schema_version"] = 3  # this board.py is schema 2
    seeded.write(doc)
    before = seeded.tickets.read_bytes()
    for args in (("set", "ACME-001", "in_progress"), ("edit", "ACME-001", "title=x"),
                 ("new", "--title", "t", "--summary", "s", "--phase", "P1", "--draft"),
                 ("usertest", "ACME-001", "0", "pass"), ("migrate",),
                 ("add-phase", "--id", "P9", "--name", "n", "--goal", "g", "--demo", "d")):
        r = seeded.fail(*args)
        assert "board is newer than this board.py; update the Slate plugin" in r.stderr
    assert seeded.tickets.read_bytes() == before
    seeded.ok("list")  # reads still work
    assert "newer" in seeded.ok("check").stdout


# --------------------------------------------------------------------------- new


NEW_STRICT = ["new", "--title", "People can log out", "--summary", "A log out button.", "--phase", "P1",
              "--story", "Priya clicks log out.", "--description", "Adds a button.",
              "--acceptance", "A button shows", "--acceptance", "Clicking it logs out",
              "--test", "When log out is clicked, then the session ends", "--areas", "backend",
              "--depends", "ACME-001", "--priority", "P1", "--estimate", "2h", "--technical", "Route /logout"]


def test_new_strict_ticket(seeded: Board) -> None:
    out = seeded.ok(*NEW_STRICT).stdout
    assert "ACME-004" in out
    t = seeded.ticket("ACME-004")
    assert t["status"] == "backlog" and t["rank"] == 4 and t["depends_on"] == ["ACME-001"]
    assert t["acceptance"] == ["A button shows", "Clicking it logs out"]
    assert list(t)[:3] == ["id", "title", "summary"]
    assert seeded.ticket("ACME-001")["unlocks"] == ["ACME-002", "ACME-004"]
    seeded.ok("check")


def test_new_strict_refuses_missing_fields(seeded: Board) -> None:
    before = seeded.tickets.read_bytes()
    r = seeded.fail("new", "--title", "Log out", "--summary", "s", "--phase", "P1")
    for f in ("story", "description", "acceptance", "test_scenarios"):
        assert f"ACME-004 {f}:" in r.stderr
    assert seeded.tickets.read_bytes() == before


def test_new_title_over_80_refused(seeded: Board) -> None:
    args = list(NEW_STRICT)
    args[2] = "x" * 81
    r = seeded.fail(*args)
    assert "title: is 81 characters" in r.stderr


def test_new_user_test_area_needs_user_test(seeded: Board) -> None:
    args = [a if a != "backend" else "frontend" for a in NEW_STRICT]
    r = seeded.fail(*args)
    assert "user_tests" in r.stderr
    seeded.ok(*args, "--user-test-json", json.dumps(USER_TEST))
    assert seeded.ticket("ACME-004")["user_tests"] == [USER_TEST]


def test_new_bad_user_test_json_is_usage_error(seeded: Board) -> None:
    seeded.fail(*NEW_STRICT, "--user-test-json", "{nope", code=2)


def test_new_draft_relaxed(seeded: Board) -> None:
    seeded.ok("new", "--title", "Maybe dark mode", "--summary", "Dark colours.", "--phase", "P1", "--draft",
              "--areas", "frontend")
    t = seeded.ticket("ACME-004")
    assert t["status"] == "draft" and "story" not in t


def test_new_after_places_rank(seeded: Board) -> None:
    seeded.ok(*NEW_STRICT, "--after", "ACME-001")
    ranks = {t["id"]: t["rank"] for t in seeded.load()["tickets"]}
    assert ranks == {"ACME-001": 1, "ACME-004": 2, "ACME-002": 3, "ACME-003": 4}
    seeded.ok("check")


def test_new_dry_run_writes_preview_only(seeded: Board) -> None:
    before = seeded.tickets.read_bytes()
    seeded.ok(*NEW_STRICT, "--dry-run")
    assert seeded.tickets.read_bytes() == before
    prev = json.loads(seeded.preview.read_text())
    assert prev["preview"] is True and prev["tickets"][0]["id"] == "ACME-004"
    seeded.ok(*NEW_STRICT)
    assert not seeded.preview.exists()


# --------------------------------------------------------------------------- add / batch


def test_add_resolves_keys_and_recomputes_unlocks(seeded: Board) -> None:
    out = seeded.ok("add", "--file", str(FIXTURES / "batch-reset.json")).stdout
    assert "ACME-004" in out and "ACME-005" in out
    doc = seeded.load()
    t4, t5 = seeded.ticket("ACME-004"), seeded.ticket("ACME-005")
    assert t4["depends_on"] == ["ACME-001"] and t5["depends_on"] == ["ACME-004"]
    assert t4["rank"] == 4 and t5["rank"] == 5
    assert t4["status"] == t5["status"] == "backlog"
    assert "key" not in t4
    assert t4["unlocks"] == ["ACME-005"]
    assert seeded.ticket("ACME-001")["unlocks"] == ["ACME-002", "ACME-004"]
    assert [p["id"] for p in doc["phases"]] == ["P1", "P2", "P3"]
    assert list(t4)[:6] == ["id", "title", "summary", "story", "visual", "description"]
    seeded.ok("check")


def test_add_after_inserts_and_moves_rest(seeded: Board) -> None:
    out = seeded.ok("add", "--file", str(FIXTURES / "batch-reset.json"), "--after", "ACME-001").stdout
    ranks = {t["id"]: t["rank"] for t in seeded.load()["tickets"]}
    assert ranks == {"ACME-001": 1, "ACME-004": 2, "ACME-005": 3, "ACME-002": 4, "ACME-003": 5}
    assert "moved down" in out
    seeded.ok("check")


def test_add_after_unknown(seeded: Board) -> None:
    r = seeded.fail("add", "--file", str(FIXTURES / "batch-reset.json"), "--after", "ACME-099")
    assert "--after ACME-099" in r.stderr


def test_add_dry_run_writes_preview_not_tickets(seeded: Board) -> None:
    before = seeded.tickets.read_bytes()
    out = seeded.ok("add", "--file", str(FIXTURES / "batch-reset.json"), "--dry-run").stdout
    assert seeded.tickets.read_bytes() == before
    assert "ACME-004  rank   4" in out and "ACME-005  rank   5" in out
    prev = json.loads(seeded.preview.read_text())
    assert list(prev) == ["preview", "phases", "tickets"]
    assert prev["preview"] is True
    assert [p["id"] for p in prev["phases"]] == ["P3"]
    assert [(t["id"], t["rank"]) for t in prev["tickets"]] == [("ACME-004", 4), ("ACME-005", 5)]
    assert prev["tickets"][1]["depends_on"] == ["ACME-004"]
    # real add removes the preview
    seeded.ok("add", "--file", str(FIXTURES / "batch-reset.json"))
    assert not seeded.preview.exists()


def test_add_as_draft(seeded: Board) -> None:
    batch = {"tickets": [{"key": "a", "title": "Idea A", "summary": "s", "phase": "P1"},
                         {"key": "b", "title": "Idea B", "summary": "s", "phase": "P1", "depends_on": ["a"]}]}
    seeded.ok("add", "--file", seeded.batch(batch), "--as-draft")
    assert seeded.ticket("ACME-004")["status"] == "draft"
    assert seeded.ticket("ACME-005")["depends_on"] == ["ACME-004"]
    # strict add of the same batch is refused
    r = seeded.fail("add", "--file", seeded.batch(batch))
    assert "'a' story: missing" in r.stderr


def test_add_refuses_strict_errors_and_writes_nothing(seeded: Board) -> None:
    batch = json.loads((FIXTURES / "batch-reset.json").read_text())
    del batch["tickets"][0]["user_tests"]
    before = seeded.tickets.read_bytes()
    r = seeded.fail("add", "--file", seeded.batch(batch))
    assert "'reset-request' user_tests" in r.stderr
    assert seeded.tickets.read_bytes() == before


def test_add_legacy_shaped_batch_ticket_is_strict(seeded: Board) -> None:
    batch = {"tickets": [{"key": "x", "title": "Old style", "phase": "P1", "areas": ["backend"],
                          "priority": "P1", "estimate": "1d", "description": "d", "acceptance": ["a"],
                          "test_scenarios": ["When a, then b"]}]}
    r = seeded.fail("add", "--file", seeded.batch(batch))
    assert "'x' summary: missing" in r.stderr and "'x' story: missing" in r.stderr


# --------------------------------------------------------------------------- batch-check


def test_batch_check_ok(seeded: Board) -> None:
    seeded.ok("batch-check", "--file", str(FIXTURES / "batch-reset.json"))


def test_batch_check_works_without_board(board: Board) -> None:
    batch = json.loads((FIXTURES / "batch-reset.json").read_text())
    batch["tickets"][0]["depends_on"] = []
    batch["phases"].append({"id": "P1", "name": "Link arrives"})
    board.ok("batch-check", "--file", board.batch(batch))


def test_batch_check_rules(seeded: Board) -> None:
    batch = {
        "phases": [{"id": "P1", "name": "Changed name"}],
        "tickets": [
            {"key": "a", "title": "t" * 81, "summary": "s", "story": "s", "description": "d",
             "acceptance": [], "test_scenarios": ["It works"], "phase": "P1", "areas": ["ui"],
             "priority": "P1", "estimate": "1d", "depends_on": ["later", "ghost"], "status": "backlog"},
            {"key": "a", "title": "dup", "summary": "s", "phase": "P7"},
            {"key": "later", "title": "Later", "summary": "s", "story": "s", "description": "d",
             "acceptance": ["x"], "test_scenarios": ["When a, then b"], "phase": "P1", "areas": ["backend"],
             "priority": "P1", "estimate": "1d"},
        ],
    }
    r = seeded.fail("batch-check", "--file", seeded.batch(batch))
    err = r.stderr
    assert "'a' title: is 81 characters" in err
    assert "'a' acceptance: must list at least one item" in err
    assert "'a' user_tests" in err
    assert "'a' status: set by board.py" in err
    assert "'later' comes later in the batch" in err
    assert "'ghost' is not a batch key or an existing ticket id" in err
    assert "key: used twice" in err
    assert "phase: 'P7' is not in the batch phases" in err
    assert "batch phase P1 id: already on the board with different details" in err
    assert "warning: 'a' test_scenarios" in r.stdout
    j = json.loads(seeded.run("batch-check", "--file", seeded.batch(batch), "--json").stdout)
    assert j["ok"] is False and j["warnings"]


def test_batch_check_key_equal_existing_id(seeded: Board) -> None:
    batch = json.loads((FIXTURES / "batch-reset.json").read_text())
    batch["tickets"][1]["key"] = "ACME-002"
    r = seeded.fail("batch-check", "--file", seeded.batch(batch))
    assert "same as an existing ticket id" in r.stderr


# --------------------------------------------------------------------------- discard-preview


def test_discard_preview(seeded: Board) -> None:
    assert "No preview" in seeded.ok("discard-preview").stdout
    seeded.ok("add", "--file", str(FIXTURES / "batch-reset.json"), "--dry-run")
    assert seeded.preview.exists()
    assert "Removed" in seeded.ok("discard-preview").stdout
    assert not seeded.preview.exists()


# --------------------------------------------------------------------------- set / promote


def test_set_happy_path_and_handoff(seeded: Board) -> None:
    seeded.ok("set", "ACME-001", "in_progress")
    seeded.ok("set", "ACME-001", "review", "--handoff", "built it")
    seeded.ok("set", "ACME-001", "done", "--handoff", "verified")
    t = seeded.ticket("ACME-001")
    assert t["status"] == "done"
    assert [h["status"] for h in t["handoff"]] == ["review", "done"]
    assert set(t["handoff"][0]) == {"date", "status", "note"}


@pytest.mark.parametrize("status", ["review", "user_testing", "done"])
def test_set_requires_handoff(seeded: Board, status: str) -> None:
    r = seeded.fail("set", "ACME-001", status)
    assert "ACME-001 handoff" in r.stderr


@pytest.mark.parametrize("status", ["in_progress", "review", "user_testing", "done"])
def test_set_refuses_when_deps_not_done(seeded: Board, status: str) -> None:
    r = seeded.fail("set", "ACME-002", status, "--handoff", "x")
    assert "ACME-002 depends_on" in r.stderr and "ACME-001 (backlog)" in r.stderr


def test_set_unknown_status_and_ticket(seeded: Board) -> None:
    assert "not one of meta.statuses" in seeded.fail("set", "ACME-001", "doing").stderr
    assert "ACME-404" in seeded.fail("set", "ACME-404", "backlog").stderr


def test_set_user_testing_needs_user_tests(seeded: Board) -> None:
    r = seeded.fail("set", "ACME-001", "user_testing", "--handoff", "try it")
    assert "ACME-001 user_tests" in r.stderr


def test_set_done_needs_required_user_test_pass(board: Board) -> None:
    board.write(base_doc([full_ticket(1, areas=["frontend"], user_tests=[USER_TEST], status="review")]))
    board.ok("set", "ACME-001", "user_testing", "--handoff", "npm run dev")
    r = board.fail("set", "ACME-001", "done", "--handoff", "x")
    assert "ACME-001 user_checks" in r.stderr and "0 'Reset with a known email'" in r.stderr
    board.ok("usertest", "ACME-001", "0", "pass", "--note", "works")
    board.ok("set", "ACME-001", "done", "--handoff", "all good")
    assert board.ticket("ACME-001")["status"] == "done"


def test_leaving_draft_is_strict(seeded: Board) -> None:
    seeded.ok("new", "--title", "Dark mode", "--summary", "Dark colours.", "--phase", "P1", "--draft")
    r = seeded.fail("set", "ACME-004", "backlog")
    assert "ACME-004 can't leave draft" in r.stderr
    for f in ("story", "description", "acceptance", "test_scenarios"):
        assert f"ACME-004 {f}: missing" in r.stderr
    assert seeded.ticket("ACME-004")["status"] == "draft"


def test_promote(seeded: Board) -> None:
    seeded.ok("new", "--title", "Dark mode", "--summary", "Dark colours.", "--phase", "P1", "--draft")
    r = seeded.fail("promote", "ACME-004")
    assert "story: missing" in r.stderr
    seeded.ok("edit", "ACME-004", "story=Priya works at night.", "description=Dark theme.",
              "acceptance:=[\"Colours are dark\"]", "test_scenarios:=[\"When dark is on, then bg is black\"]")
    seeded.ok("promote", "ACME-004")
    assert seeded.ticket("ACME-004")["status"] == "backlog"
    assert "not draft" in seeded.fail("promote", "ACME-004").stderr


def test_promote_refused_while_dependency_is_draft(seeded: Board) -> None:
    batch = {"tickets": [{"key": "a", "title": "A", "summary": "s", "phase": "P1"},
                         {"key": "b", "title": "B", "summary": "s", "phase": "P1", "depends_on": ["a"]}]}
    seeded.ok("add", "--file", seeded.batch(batch), "--as-draft")
    full = {"story": "s", "description": "d", "acceptance": ["a"], "test_scenarios": ["When a, then b"],
            "areas": ["backend"], "priority": "P1", "estimate": "1d", "labels": []}
    patch = seeded.root / "patch.json"
    patch.write_text(json.dumps(full))
    seeded.ok("edit", "ACME-005", "--file", str(patch))
    r = seeded.fail("promote", "ACME-005")
    assert "ACME-005 depends_on: ACME-004 is a draft" in r.stderr


# --------------------------------------------------------------------------- usertest


@pytest.fixture
def ui_board(board: Board) -> Board:
    board.write(base_doc([full_ticket(1, areas=["frontend"], user_tests=[USER_TEST], status="user_testing")]))
    return board


def test_usertest_pass(ui_board: Board) -> None:
    ui_board.ok("usertest", "ACME-001", "0", "pass", "--note", "fine")
    t = ui_board.ticket("ACME-001")
    assert t["user_checks"]["0"]["result"] == "pass" and t["user_checks"]["0"]["note"] == "fine"
    assert t["status"] == "user_testing"
    assert list(t)[-1] == "user_checks"


def test_usertest_fail_moves_back(ui_board: Board) -> None:
    out = ui_board.ok("usertest", "ACME-001", "0", "fail", "--note", "button missing").stdout
    t = ui_board.ticket("ACME-001")
    assert t["status"] == "in_progress" and "moved back" in out
    assert t["handoff"][-1]["status"] == "in_progress"
    assert t["handoff"][-1]["note"] == "User test failed: Reset with a known email: button missing"


def test_usertest_bad_index(ui_board: Board) -> None:
    r = ui_board.fail("usertest", "ACME-001", "3", "pass")
    assert "ACME-001 user_tests: no user test at index 3" in r.stderr
    ui_board.fail("usertest", "ACME-001", "0", "maybe", code=2)


# --------------------------------------------------------------------------- edit


def test_edit_string_and_json(seeded: Board) -> None:
    seeded.ok("edit", "ACME-003", "title=A better title", "labels:=[\"x\", \"y\"]", "estimate=3d")
    t = seeded.ticket("ACME-003")
    assert t["title"] == "A better title" and t["labels"] == ["x", "y"] and t["estimate"] == "3d"


def test_edit_value_with_equals_sign(seeded: Board) -> None:
    seeded.ok("edit", "ACME-003", "technical=set a=b in config")
    assert seeded.ticket("ACME-003")["technical"] == "set a=b in config"


def test_edit_new_key_goes_to_canonical_place(seeded: Board) -> None:
    seeded.ok("edit", "ACME-003", "visual=```\\na -> b\\n```")
    keys = list(seeded.ticket("ACME-003"))
    assert keys.index("visual") == keys.index("story") + 1


@pytest.mark.parametrize("key", ["id", "rank", "status", "handoff", "user_checks", "unlocks"])
def test_edit_refuses_protected(seeded: Board, key: str) -> None:
    before = seeded.tickets.read_bytes()
    r = seeded.fail("edit", "ACME-001", f"{key}=x")
    assert f"ACME-001 {key}: can't be changed with edit" in r.stderr
    assert seeded.tickets.read_bytes() == before


def test_edit_depends_on_recomputes_unlocks(seeded: Board) -> None:
    seeded.ok("edit", "ACME-003", "depends_on:=[\"ACME-001\"]")
    assert seeded.ticket("ACME-001")["unlocks"] == ["ACME-002", "ACME-003"]
    seeded.ok("edit", "ACME-002", "depends_on:=[]")
    assert seeded.ticket("ACME-001")["unlocks"] == ["ACME-003"]


def test_edit_invalid_result_refused(seeded: Board) -> None:
    before = seeded.tickets.read_bytes()
    r = seeded.fail("edit", "ACME-001", "depends_on:=[\"ACME-003\"]")  # 003 ranks after 001
    assert "ACME-001 rank" in r.stderr
    r = seeded.fail("edit", "ACME-001", "story:=null")
    assert "ACME-001 story: missing" in r.stderr
    assert seeded.tickets.read_bytes() == before


def test_edit_bad_json_and_bad_form(seeded: Board) -> None:
    seeded.fail("edit", "ACME-001", "labels:=[oops", code=2)
    seeded.fail("edit", "ACME-001", "justakey", code=2)
    seeded.fail("edit", "ACME-001", code=2)


def test_edit_patch_file(seeded: Board) -> None:
    p = seeded.root / "patch.json"
    p.write_text(json.dumps({"summary": "New summary", "acceptance": ["one", "two"]}))
    seeded.ok("edit", "ACME-002", "--file", str(p))
    t = seeded.ticket("ACME-002")
    assert t["summary"] == "New summary" and t["acceptance"] == ["one", "two"]
    p.write_text(json.dumps({"rank": 9}))
    assert "rank: can't be changed" in seeded.fail("edit", "ACME-002", "--file", str(p)).stderr


# --------------------------------------------------------------------------- rerank / add-phase


def test_rerank_after_and_first(seeded: Board) -> None:
    seeded.ok("rerank", "ACME-003", "--first")
    ranks = {t["id"]: t["rank"] for t in seeded.load()["tickets"]}
    assert ranks == {"ACME-003": 1, "ACME-001": 2, "ACME-002": 3}
    seeded.ok("rerank", "ACME-003", "--after", "ACME-002")
    ranks = {t["id"]: t["rank"] for t in seeded.load()["tickets"]}
    assert ranks == {"ACME-001": 1, "ACME-002": 2, "ACME-003": 3}


def test_rerank_makes_ranks_contiguous(board: Board) -> None:
    board.write(base_doc([full_ticket(1, rank=10), full_ticket(2, rank=20), full_ticket(3, rank=30)]))
    board.ok("rerank", "ACME-001", "--after", "ACME-002")
    ranks = {t["id"]: t["rank"] for t in board.load()["tickets"]}
    assert ranks == {"ACME-002": 1, "ACME-001": 2, "ACME-003": 3}


def test_rerank_refuses_before_dependency(seeded: Board) -> None:
    before = seeded.tickets.read_bytes()
    r = seeded.fail("rerank", "ACME-002", "--first")
    assert "ACME-002 rank" in r.stderr and "dependency ACME-001" in r.stderr
    assert seeded.tickets.read_bytes() == before
    seeded.fail("rerank", "ACME-002", code=2)
    seeded.fail("rerank", "ACME-002", "--after", "ACME-002")


def test_add_phase(seeded: Board) -> None:
    seeded.ok("add-phase", "--id", "P3", "--name", "Safe", "--goal", "Links expire", "--demo", "Old link fails")
    assert seeded.load()["phases"][-1] == {"id": "P3", "name": "Safe", "goal": "Links expire",
                                          "demo": "Old link fails"}
    r = seeded.fail("add-phase", "--id", "P3", "--name", "x", "--goal", "g", "--demo", "d")
    assert "phase P3 id: already exists" in r.stderr


# --------------------------------------------------------------------------- migrate / upgrade


def test_migrate_legacy_mini(board: Board) -> None:
    shutil.copy(FIXTURES / "legacy-forge-mini.json", board.tickets)
    assert "meta prefix: missing" in board.fail("check").stderr
    out = board.ok("migrate").stdout
    assert "added meta.prefix = FORGE" in out
    m = board.load()["meta"]
    assert m["schema_version"] == 2 and m["slate_version"] == "0.2.0"
    assert m["statuses"] == ["draft", "backlog", "ready", "in_progress", "review", "user_testing",
                             "merge_ready", "done"]
    assert m["user_test_areas"] == ["frontend", "ui"]
    assert list(m)[:4] == ["project", "prefix", "slate_version", "schema_version"]
    # tickets are untouched (additive only)
    orig = json.loads((FIXTURES / "legacy-forge-mini.json").read_text())
    assert board.load()["tickets"] == orig["tickets"]
    board.ok("check")
    assert "already at schema 2" in board.ok("migrate").stdout


def test_migrate_bumps_slate_version(seeded: Board) -> None:
    doc = seeded.load()
    doc["meta"]["slate_version"] = "0.0.1"
    seeded.write(doc)
    assert "was 0.0.1" in seeded.ok("migrate").stdout
    assert seeded.load()["meta"]["slate_version"] == "0.2.0"


@pytest.mark.skipif(not FORGE_BOARD.exists(), reason="forge/kanban/tickets.json not next to this repo")
def test_migrate_real_forge_board(board: Board) -> None:
    shutil.copy(FORGE_BOARD, board.tickets)
    original = json.loads(FORGE_BOARD.read_text(encoding="utf-8"))
    pre = board.run("check")
    assert pre.returncode == 1 and pre.stderr.count("error: ") == 1 and "meta prefix: missing" in pre.stderr
    board.ok("migrate")
    r = board.ok("check")
    assert "error" not in r.stderr
    assert r.stdout.count("warning: ") > 0
    after = board.load()
    assert after["tickets"] == original["tickets"] and after["phases"] == original["phases"]
    assert board.ok("next", "--brief").stdout.startswith("Slate 0.2.0: ")
    board.ok("show", "FORGE-001")
    board.ok("status")


def fake_assets(root: Path, version: str = "0.1.0") -> Path:
    assets = root / "assets" / "board"
    assets.mkdir(parents=True)
    shutil.copy(BOARD_SRC, assets / "board.py")
    (assets / "index.html").write_text(f'<meta name="slate-version" content="{version}">\n')
    (assets / "README.md").write_text("# Slate board\n")
    return assets


def test_upgrade_copies_files_then_migrates(board: Board) -> None:
    shutil.copy(FIXTURES / "legacy-forge-mini.json", board.tickets)
    (board.dir / "index.html").write_text("old board\n")
    assets = fake_assets(board.root)
    r = board.ok("upgrade", "--from", str(assets))
    assert "Updated kanban/index.html" in r.stdout and "Migrated kanban/tickets.json" in r.stdout
    assert (board.dir / "index.html").read_text() == (assets / "index.html").read_text()
    assert (board.dir / "README.md").exists()
    assert board.load()["meta"]["schema_version"] == 2
    assert not list(board.dir.glob(".*.tmp"))


def test_upgrade_missing_assets(board: Board) -> None:
    board.ok("init", "--project", "Acme", "--prefix", "ACME")
    empty = board.root / "empty"
    empty.mkdir()
    r = board.fail("upgrade", "--from", str(empty))
    assert "missing" in r.stderr


# --------------------------------------------------------------------------- file format


def test_atomic_write_leaves_no_temp_files(seeded: Board) -> None:
    seeded.ok("set", "ACME-001", "in_progress")
    seeded.ok("add", "--file", str(FIXTURES / "batch-reset.json"), "--dry-run")
    seeded.fail("set", "ACME-002", "in_progress")
    assert sorted(p.name for p in seeded.dir.iterdir()) == ["board.py", "preview.json", "tickets.json"]


def test_format_stable_round_trip(seeded: Board) -> None:
    seeded.ok("add", "--file", str(FIXTURES / "batch-reset.json"))
    seeded.ok("set", "ACME-001", "in_progress")
    text = seeded.tickets.read_text(encoding="utf-8")
    assert text.endswith("}\n") and not text.endswith("\n\n")
    assert json.dumps(json.loads(text), indent=2, ensure_ascii=False) + "\n" == text
    # a no-op-shaped write (edit to same value) leaves the file byte-identical
    before = seeded.tickets.read_bytes()
    seeded.ok("edit", "ACME-003", f"title={seeded.ticket('ACME-003')['title']}")
    assert seeded.tickets.read_bytes() == before


def test_non_ascii_kept_and_key_order_preserved(board: Board) -> None:
    doc = base_doc([full_ticket(1, summary="Café — naïve ✓", extra_field="kept")])
    doc["meta"] = dict(reversed(list(doc["meta"].items())))  # odd but valid key order
    board.write(doc)
    before = board.tickets.read_bytes()
    board.ok("edit", "ACME-001", "estimate=1d")  # same value
    assert board.tickets.read_bytes() == before
    board.ok("edit", "ACME-001", "estimate=2d")
    text = board.tickets.read_text(encoding="utf-8")
    assert "Café — naïve ✓" in text and "\\u" not in text
    assert list(json.loads(text)["meta"]) == list(doc["meta"])
    assert list(board.ticket("ACME-001"))[-1] == "extra_field"


@pytest.mark.skipif(not FORGE_BOARD.exists(), reason="forge/kanban/tickets.json not next to this repo")
def test_forge_board_round_trip_byte_identical(board: Board) -> None:
    shutil.copy(FORGE_BOARD, board.tickets)
    board.ok("migrate")
    once = board.tickets.read_bytes()
    board.ok("set", "FORGE-091", "backlog")  # same status: rewrites the file
    assert board.tickets.read_bytes() == once


# --------------------------------------------------------------------------- code changes: link, set-meta


SHA40 = "3f9c2a71b0d84e5f6a1c9e2b7d4038a5c6e1f902"


def git(cwd: Path, *args: str) -> str:
    r = subprocess.run(["git", "-c", "user.name=Test", "-c", "user.email=test@example.com",
                        "-c", "commit.gpgsign=false", *args],
                       cwd=str(cwd), capture_output=True, text=True, check=True)
    return r.stdout.strip()


def git_repo(board: Board, branch: str = "feat/reset") -> str:
    """Make board.root a git repo with one commit; returns the commit's full sha."""
    git(board.root, "init", "-q", "-b", branch)
    (board.root / "app.txt").write_text("hello\n")
    git(board.root, "add", "app.txt")
    git(board.root, "commit", "-q", "-m", "Add the reset page")
    return git(board.root, "rev-parse", "HEAD")


def has_fix(stderr: str) -> bool:
    return "fix: " in stderr or "ask the user: " in stderr


def test_link_head_stores_full_sha_subject_branch(seeded: Board) -> None:
    sha = git_repo(seeded)
    out = seeded.ok("link", "ACME-001", "--commit", "HEAD").stdout
    assert sha[:7] in out
    c = seeded.ticket("ACME-001")["commits"]
    assert len(c) == 1
    assert c[0]["sha"] == sha and len(sha) == 40
    assert c[0]["message"] == "Add the reset page"
    assert c[0]["branch"] == "feat/reset"
    assert re.match(r"^\d{4}-\d{2}-\d{2}$", c[0]["date"])
    assert list(c[0]) == ["sha", "date", "message", "branch"]
    keys = list(seeded.ticket("ACME-001"))
    assert keys.index("commits") > keys.index("handoff")


def test_link_same_sha_twice_is_noop(seeded: Board) -> None:
    sha = git_repo(seeded)
    seeded.ok("link", "ACME-001", "--commit", "HEAD")
    before = seeded.tickets.read_bytes()
    out = seeded.ok("link", "ACME-001", "--commit", sha, "--commit", sha[:9]).stdout
    assert "already linked" in out
    assert seeded.tickets.read_bytes() == before
    assert len(seeded.ticket("ACME-001")["commits"]) == 1


def test_link_literal_sha_without_git(seeded: Board) -> None:
    seeded.ok("link", "ACME-001", "--commit", "ABC1234", "--message", "Fix the thing")
    seeded.ok("link", "ACME-001", "--commit", SHA40)
    c = seeded.ticket("ACME-001")["commits"]
    assert c[0] == {"sha": "abc1234", "date": c[0]["date"], "message": "Fix the thing"}
    assert c[1]["sha"] == SHA40 and c[1]["message"] == "" and "branch" not in c[1]


def test_link_bad_ref_errors(seeded: Board) -> None:
    before = seeded.tickets.read_bytes()
    r = seeded.fail("link", "ACME-001", "--commit", "HEAD")  # no git repo here
    assert "ACME-001 commits: 'HEAD'" in r.stderr and has_fix(r.stderr)
    git_repo(seeded)
    r = seeded.fail("link", "ACME-001", "--commit", "no-such-branch")
    assert "'no-such-branch' is not a commit" in r.stderr and has_fix(r.stderr)
    assert "commits" not in seeded.ticket("ACME-001")
    seeded.fail("link", "ACME-001", code=2)
    seeded.fail("link", "ACME-099", "--commit", SHA40)
    assert seeded.tickets.read_bytes() == before


@pytest.mark.parametrize("url,number", [
    ("https://github.com/acme/app/pull/12", 12),
    ("https://gitlab.com/acme/app/-/merge_requests/7", 7),
    ("https://gitlab.example.com/g/sub/app/-/merge_requests/301/diffs", 301),
    ("https://example.com/review/abc", None),
])
def test_link_pr_number_parsing(seeded: Board, url: str, number: Any) -> None:
    seeded.ok("link", "ACME-001", "--pr", url)
    pr = seeded.ticket("ACME-001")["pr"]
    assert pr["url"] == url and pr["state"] == "draft"
    assert pr.get("number") == number


def test_link_pr_state_and_title_update(seeded: Board) -> None:
    r = seeded.fail("link", "ACME-001", "--pr-state", "merged")
    assert "has no pull request yet" in r.stderr and has_fix(r.stderr)
    url = "https://github.com/acme/app/pull/12"
    seeded.ok("link", "ACME-001", "--pr", url, "--pr-title", "Reset flow", "--pr-state", "open")
    seeded.ok("link", "ACME-001", "--pr-state", "merged")
    pr = seeded.ticket("ACME-001")["pr"]
    assert pr == {"url": url, "number": 12, "title": "Reset flow", "state": "merged"}
    seeded.ok("link", "ACME-001", "--pr", url)  # same url again keeps state and title
    assert seeded.ticket("ACME-001")["pr"]["state"] == "merged"
    seeded.ok("link", "ACME-001", "--pr", "https://github.com/acme/app/pull/13")  # new PR replaces it
    assert seeded.ticket("ACME-001")["pr"] == {"url": "https://github.com/acme/app/pull/13", "number": 13,
                                              "state": "draft"}
    seeded.fail("link", "ACME-001", "--pr-state", "shipped", code=2)
    r = seeded.fail("link", "ACME-001", "--pr", "ftp://example.com/x")
    assert "pr.url" in r.stderr and has_fix(r.stderr)


def test_link_allowed_on_done_ticket(board: Board) -> None:
    board.write(base_doc([full_ticket(1, status="done")]))
    board.ok("link", "ACME-001", "--commit", SHA40, "--pr", "https://github.com/a/b/pull/1", "--pr-state", "merged")
    t = board.ticket("ACME-001")
    assert t["status"] == "done" and t["commits"][0]["sha"] == SHA40 and t["pr"]["state"] == "merged"


@pytest.mark.parametrize("key", ["commits", "pr", "done_without"])
def test_edit_refuses_code_fields(seeded: Board, key: str) -> None:
    r = seeded.fail("edit", "ACME-001", f"{key}:=[]")
    assert f"ACME-001 {key}: can't be changed with edit" in r.stderr
    assert "board.py link ACME-001" in r.stderr or "--no-code" in r.stderr


@pytest.mark.parametrize("field,value,fragment", [
    ("commits", [{"sha": "xyz", "date": "2026-09-26", "message": "m"}], "commits[0].sha: must be 7 to 40 hex"),
    ("commits", [{"sha": "abc123", "date": "2026-09-26", "message": "m"}], "commits[0].sha: must be 7 to 40 hex"),
    ("commits", [{"sha": SHA40, "date": "26/09/2026", "message": "m"}], "commits[0].date: must be a date"),
    ("commits", [{"sha": SHA40, "date": "2026-09-26"}, {"sha": SHA40, "date": "2026-09-26"}],
     f"commits[1].sha: {SHA40} is listed twice"),
    ("commits", "abc1234", "commits: must be a list"),
    ("pr", {"url": "github.com/a/b/pull/1", "state": "open"}, "pr.url: must be an http"),
    ("pr", {"url": "https://github.com/a/b/pull/1", "state": "shipped"}, "pr.state: 'shipped' must be one of"),
    ("pr", {"url": "https://github.com/a/b/pull/1"}, "pr.state"),
    ("pr", {"url": "https://github.com/a/b/pull/1", "state": "open", "number": "1"}, "pr.number"),
    ("done_without", {"why": "x"}, "done_without: must be"),
])
def test_code_fields_validation(board: Board, field: str, value: Any, fragment: str) -> None:
    assert_error(board, base_doc([full_ticket(1, **{field: value})]), f"ACME-001 {fragment}")
    assert has_fix(board.run("check").stderr)


def test_meta_repo_url_validation(board: Board) -> None:
    doc = base_doc([full_ticket(1)])
    doc["meta"]["repo_url"] = "git@github.com:acme/app.git"
    assert_error(board, doc, "meta repo_url: must be an http")


def test_show_code_changes_section(board: Board) -> None:
    t = full_ticket(1, plan_doc="docs/plans/x.md",
                    handoff=[{"date": "2026-09-26", "status": "review", "note": "Built it."}],
                    commits=[{"sha": SHA40, "date": "2026-09-21", "message": "Add the page", "branch": "b"}],
                    pr={"url": "https://github.com/acme/app/pull/42", "number": 42, "state": "merged"})
    board.write(base_doc([t]))
    out = board.ok("show", "ACME-001").stdout
    assert "Code changes\n  PR: https://github.com/acme/app/pull/42 (merged)" in out
    assert "  3f9c2a7 Add the page (2026-09-21)" in out
    assert out.index("Plan doc") < out.index("Code changes") < out.index("History")
    j = json.loads(board.ok("show", "ACME-001", "--json").stdout)
    assert j["commits"][0]["sha"] == SHA40 and j["pr"]["number"] == 42
    board.write(base_doc([full_ticket(1)]))
    assert "Code changes" not in board.ok("show", "ACME-001").stdout


def test_set_meta_allowed_keys(seeded: Board) -> None:
    seeded.ok("set-meta", "repo_url=https://gitlab.com/acme/app.git/", "project=Acme Two",
              'areas:=["backend", "frontend", "infra", "ui"]', 'user_test_areas:=["ui"]')
    m = seeded.load()["meta"]
    assert m["repo_url"] == "https://gitlab.com/acme/app" and m["project"] == "Acme Two"
    assert m["areas"][-1] == "ui" and m["user_test_areas"] == ["ui"]
    assert list(m).index("repo_url") == list(m).index("prefix") + 1
    seeded.ok("set-meta", "repo_url:=null")
    assert "repo_url" not in seeded.load()["meta"]


@pytest.mark.parametrize("arg", ["prefix=XX", "statuses:=[]", "generated=2020-01-01", "areas=backend",
                                 "repo_url=not-a-url", "project="])
def test_set_meta_refused(seeded: Board, arg: str) -> None:
    before = seeded.tickets.read_bytes()
    r = seeded.fail("set-meta", arg)
    assert "meta " in r.stderr and has_fix(r.stderr)
    assert seeded.tickets.read_bytes() == before


def test_set_meta_user_test_areas_that_break_tickets_refused(seeded: Board) -> None:
    r = seeded.fail("set-meta", 'user_test_areas:=["backend"]')
    assert "user_tests" in r.stderr and has_fix(r.stderr)


def test_init_repo_url(board: Board) -> None:
    board.ok("init", "--project", "Acme", "--prefix", "ACME", "--repo-url", "https://github.com/acme/app")
    m = board.load()["meta"]
    assert m["repo_url"] == "https://github.com/acme/app" and list(m)[:3] == ["project", "prefix", "repo_url"]
    board.ok("check")


def test_demo_fixture_is_valid_and_has_code_links(board: Board) -> None:
    shutil.copy(FIXTURES / "board-demo" / "tickets.json", board.tickets)
    board.ok("check")
    doc = board.load()
    assert doc["meta"]["repo_url"] == "https://github.com/acme/acme-app"
    by = {t["id"]: t for t in doc["tickets"]}
    assert len(by["ACME-002"]["commits"]) == 2 and by["ACME-002"]["pr"]["state"] == "merged"
    assert len(by["ACME-003"]["commits"]) == 1 and by["ACME-003"]["pr"]["state"] == "draft"


def test_status_lists_drafts(seeded: Board) -> None:
    doc = seeded.load()
    doc["tickets"].append({"id": "ACME-004", "title": "Half an idea", "summary": "s", "phase": "P1",
                           "rank": 4, "status": "draft", "depends_on": []})
    seeded.write(doc)
    out = seeded.ok("status").stdout
    assert "Drafts (not ready to work)\n  ACME-004  Half an idea" in out
    j = json.loads(seeded.ok("status", "--json").stdout)
    assert j["drafts"] == [{"id": "ACME-004", "title": "Half an idea"}]
    seeded.write(base_doc([full_ticket(1)]))
    assert "Drafts (not ready to work)\n  nothing" in seeded.ok("status").stdout
    assert json.loads(seeded.ok("status", "--json").stdout)["drafts"] == []


# --------------------------------------------------------------------------- done needs code


def test_done_refused_without_commit(seeded: Board) -> None:
    git_repo(seeded)
    before = seeded.tickets.read_bytes()
    r = seeded.fail("set", "ACME-001", "done", "--handoff", "Built it")
    assert "ACME-001 commits: has no commits linked" in r.stderr
    assert "fix: python3 kanban/board.py link ACME-001 --commit HEAD" in r.stderr
    assert "--no-code" in r.stderr
    assert seeded.tickets.read_bytes() == before


def test_done_refused_with_remote_but_no_pr(seeded: Board) -> None:
    git_repo(seeded)
    git(seeded.root, "remote", "add", "origin", "https://example.com/acme/app.git")
    seeded.ok("link", "ACME-001", "--commit", "HEAD")
    r = seeded.fail("set", "ACME-001", "done", "--handoff", "Built it")
    assert "ACME-001 pr: no pull request linked" in r.stderr
    assert "board.py link ACME-001 --pr URL" in r.stderr and "--no-pr" in r.stderr
    assert seeded.ticket("ACME-001")["status"] == "backlog"


def test_done_passes_with_commit_and_pr(seeded: Board) -> None:
    git_repo(seeded)
    git(seeded.root, "remote", "add", "origin", "https://example.com/acme/app.git")
    seeded.ok("link", "ACME-001", "--commit", "HEAD", "--pr", "https://github.com/a/b/pull/3", "--pr-state", "merged")
    r = seeded.ok("set", "ACME-001", "done", "--handoff", "Built it")
    assert "warning" not in r.stdout
    t = seeded.ticket("ACME-001")
    assert t["status"] == "done" and "done_without" not in t


def test_done_passes_with_commit_and_no_remote(seeded: Board) -> None:
    git_repo(seeded)
    seeded.ok("link", "ACME-001", "--commit", "HEAD")
    seeded.ok("set", "ACME-001", "done", "--handoff", "Built it")
    assert seeded.ticket("ACME-001")["status"] == "done"


def test_done_no_code(seeded: Board) -> None:
    git_repo(seeded)
    git(seeded.root, "remote", "add", "origin", "https://example.com/acme/app.git")
    seeded.ok("set", "ACME-001", "done", "--handoff", "Wrote the doc", "--no-code", "docs only")
    t = seeded.ticket("ACME-001")
    assert t["status"] == "done" and t["done_without"] == {"code": "docs only"}
    assert t["handoff"][-1]["note"] == "Wrote the doc (no code: docs only)"
    assert "Closed without code: docs only" in seeded.ok("show", "ACME-001").stdout
    seeded.ok("check")


def test_done_no_pr(seeded: Board) -> None:
    git_repo(seeded)
    git(seeded.root, "remote", "add", "origin", "https://example.com/acme/app.git")
    r = seeded.fail("set", "ACME-001", "done", "--handoff", "Built it", "--no-pr", "pushed to main")
    assert "has no commits linked" in r.stderr  # --no-pr still needs a commit
    seeded.ok("link", "ACME-001", "--commit", "HEAD")
    seeded.ok("set", "ACME-001", "done", "--handoff", "Built it", "--no-pr", "pushed to main")
    t = seeded.ticket("ACME-001")
    assert t["done_without"] == {"pr": "pushed to main"}
    assert t["handoff"][-1]["note"] == "Built it (no PR: pushed to main)"


def test_done_escape_hatch_misuse(seeded: Board) -> None:
    r = seeded.fail("set", "ACME-001", "in_progress", "--no-code", "x")
    assert "--no-code only goes with done" in r.stderr and has_fix(r.stderr)
    r = seeded.fail("set", "ACME-001", "done", "--handoff", "x", "--no-code", "  ")
    assert "needs a reason" in r.stderr and has_fix(r.stderr)
    seeded.fail("set", "ACME-001", "done", "--handoff", "x", "--no-code", "a", "--no-pr", "b", code=2)


def test_done_unknown_sha_refused(seeded: Board) -> None:
    git_repo(seeded)
    seeded.ok("link", "ACME-001", "--commit", SHA40)  # literal: not in this repo
    r = seeded.fail("set", "ACME-001", "done", "--handoff", "Built it")
    assert f"ACME-001 commits: {SHA40[:12]} is not a commit in this git repository" in r.stderr
    assert has_fix(r.stderr)


def test_done_without_git_warns_and_passes(seeded: Board) -> None:
    r = seeded.ok("set", "ACME-001", "done", "--handoff", "Built it")
    assert "warning: git isn't available here" in r.stdout
    assert seeded.ticket("ACME-001")["status"] == "done"


def test_existing_done_tickets_without_commits_still_pass_check(board: Board) -> None:
    board.write(base_doc([full_ticket(1, status="done"), full_ticket(2, status="done")]))
    git_repo(board)
    git(board.root, "remote", "add", "origin", "https://example.com/acme/app.git")
    board.ok("check")
    board.ok("edit", "ACME-002", "estimate=2d")  # other writes still work


# --------------------------------------------------------------------------- actionable errors


REFUSALS = [
    (("set", "ACME-099", "done"), 1),
    (("set", "ACME-002", "in_progress"), 1),
    (("set", "ACME-001", "review"), 1),
    (("set", "ACME-001", "bogus"), 1),
    (("set", "ACME-001", "user_testing", "--handoff", "x"), 1),
    (("set", "ACME-001", "in_progress", "--no-pr", "x"), 1),
    (("edit", "ACME-001", "rank=2"), 1),
    (("edit", "ACME-001", "status=done"), 1),
    (("edit", "ACME-001", "handoff:=[]"), 1),
    (("edit", "ACME-001", "story:=null"), 1),
    (("edit", "ACME-001", 'depends_on:=["ACME-003"]'), 1),
    (("edit", "ACME-001", 'depends_on:=["ACME-042"]'), 1),
    (("edit", "ACME-001", 'depends_on:=["ACME-002"]'), 1),
    (("edit", "ACME-001", "phase=P9"), 1),
    (("edit", "ACME-001", "labels:=[oops"), 2),
    (("edit", "ACME-001", "justakey"), 2),
    (("edit", "ACME-001"), 2),
    (("rerank", "ACME-001", "--after", "ACME-001"), 1),
    (("rerank", "ACME-001", "--after", "ACME-077"), 1),
    (("promote", "ACME-001"), 1),
    (("add-phase", "--id", "P1", "--name", "n", "--goal", "g", "--demo", "d"), 1),
    (("usertest", "ACME-001", "0", "pass"), 1),
    (("link", "ACME-001", "--commit", "not-hex"), 1),
    (("link", "ACME-001", "--pr", "ftp://x"), 1),
    (("link", "ACME-001", "--pr-state", "merged"), 1),
    (("link", "ACME-001"), 2),
    (("set-meta", "prefix=XX"), 1),
    (("set-meta", "areas=backend"), 1),
    (("set-meta",), 2),
    (("new", "--title", "T", "--summary", "s", "--phase", "P1"), 1),
    (("new", "--title", "T", "--summary", "s", "--phase", "P1", "--draft", "--after", "ACME-099"), 1),
    (("init", "--project", "Acme", "--prefix", "ACME"), 1),
    (("add", "--file", "missing.json"), 1),
    (("list", "-1"), 2),
    (("bogus-command",), 2),
    (("show",), 2),
    (("upgrade", "--from", "nowhere"), 1),
    # v0.2 refusals (seeded is a v1 board; tests/test_board_v2.py covers them on a v2 board too)
    (("set", "ACME-001,ACME-002", "in_progress"), 1),
    (("set", "ACME-001", "merge_ready", "--handoff", "x"), 1),
    (("set", "ACME-002", "done", "--handoff", "x", "--ignore-deps", "r"), 1),
    (("set", "ACME-002", "backlog", "--ignore-deps", "r"), 1),
    (("set", "ACME-002", "in_progress", "--ignore-deps", " "), 1),
    (("set", ",", "in_progress"), 2),
    (("link", "ACME-001,ACME-099", "--pr", "https://github.com/a/b/pull/1"), 1),
    (("edit", "ACME-001", "title+=x"), 1),
    (("edit", "ACME-001", "item_checks:={}"), 1),
    (("edit-phase", "P9", "name=x"), 1),
    (("edit-phase", "P1", "id=P3"), 1),
    (("edit-phase", "P1", "unscheduled=yes"), 1),
    (("edit-phase", "P1"), 2),
    (("rename-phase", "P1", "P2"), 1),
    (("rename-phase", "P1", "bad id"), 1),
    (("remove-phase", "P1"), 1),
    (("remove-phase", "P1", "--move-to", "P9"), 1),
    (("reorder-phases", "P1"), 1),
    (("add-phase", "--id", "bad id", "--name", "n", "--goal", "g", "--demo", "d"), 1),
    (("new", "--title", "T", "--summary", "s", "--phase", "P1", "--draft", "--fixes", "ACME-099"), 1),
    (("new", "--title", "T", "--summary", "s", "--phase", "P1", "--draft", "--fixes", "ACME-001",
      "--after", "ACME-002"), 2),
    (("check-item", "ACME-001", "acceptance", "5"), 1),
    (("uncheck-item", "ACME-001", "test", "9"), 1),
    (("check-item", "ACME-001", "story", "0"), 2),
    (("export", "--json", "--status", "doing"), 1),
    (("list", "--phase", "P9"), 1),
    (("status", "--status", "nope"), 1),
    (("set-meta", "check_quiet_optional=yes"), 1),
]


@pytest.mark.parametrize("args,code", REFUSALS, ids=[" ".join(a) for a, _ in REFUSALS])
def test_every_refusal_says_how_to_fix(seeded: Board, args: Any, code: int) -> None:
    r = seeded.fail(*args, code=code)
    assert has_fix(r.stderr), r.stderr
    for ln in r.stderr.splitlines():  # no leftover placeholder commands from the old wording
        assert "board.py ID" not in ln


def test_fix_lines_name_real_ids(seeded: Board) -> None:
    r = seeded.fail("set", "ACME-002", "in_progress")
    assert "fix: python3 kanban/board.py show ACME-001" in r.stderr
    r = seeded.fail("edit", "ACME-001", 'depends_on:=["ACME-003"]')
    assert "fix: python3 kanban/board.py rerank ACME-001 --after ACME-003" in r.stderr
    r = seeded.fail("set", "ACME-01", "done")
    assert "did you mean ACME-001?" in r.stderr


def test_refusals_on_bad_or_newer_board_say_how_to_fix(seeded: Board) -> None:
    doc = seeded.load()
    doc["tickets"][0]["status"] = "shipped"
    seeded.write(doc)
    r = seeded.fail("edit", "ACME-002", "estimate=2d")
    assert "has errors, so nothing was changed" in r.stderr
    assert "ACME-001 status: 'shipped'" in r.stderr and "fix: python3 kanban/board.py set ACME-001" in r.stderr
    doc["tickets"][0]["status"] = "backlog"
    doc["meta"]["schema_version"] = 99
    seeded.write(doc)
    r = seeded.fail("edit", "ACME-002", "estimate=2d")
    assert "newer" in r.stderr and "ask the user:" in r.stderr
    seeded.tickets.write_text("{ not json")
    r = seeded.fail("edit", "ACME-002", "estimate=2d")
    assert "not valid JSON" in r.stderr and "ask the user:" in r.stderr
    seeded.tickets.unlink()
    r = seeded.fail("show", "ACME-001")
    assert "fix: python3 kanban/board.py init" in r.stderr


def test_check_and_batch_check_json_have_fix(board: Board) -> None:
    t = full_ticket(1, rank=2)
    t2 = full_ticket(2, rank=1, depends_on=["ACME-001"], phase="P7")
    board.write(base_doc([t, t2]))
    j = check_json(board)
    assert not j["ok"] and j["errors"]
    assert all(isinstance(e["fix"], list) and e["fix"] for e in j["errors"] + j["warnings"])
    board.write(base_doc([full_ticket(1)]))
    p = board.batch({"tickets": [{"key": "a", "title": "T"}]})
    r = board.run("batch-check", "--file", p, "--json")
    assert r.returncode == 1
    bj = json.loads(r.stdout)
    assert bj["errors"] and all(e["fix"] and p in e["fix"][0] for e in bj["errors"])
    r = board.fail("batch-check", "--file", p)
    assert f"fix: in {p}, fix \"summary\" on 'a'" in r.stderr


def test_empty_required_string_is_an_error(tmp_path):
    import json as _json, shutil, subprocess, sys as _sys
    from pathlib import Path as _P
    k = tmp_path / "kanban"; k.mkdir()
    shutil.copy(_P(__file__).resolve().parents[1] / "plugins/slate/assets/board/board.py", k / "board.py")
    run = lambda *a: subprocess.run([_sys.executable, str(k / "board.py"), *a], capture_output=True, text=True, cwd=tmp_path)
    assert run("init", "--project", "Acme", "--prefix", "ACME").returncode == 0
    assert run("add-phase", "--id", "P1", "--name", "One", "--goal", "g", "--demo", "d").returncode == 0
    assert run("new", "--title", "T", "--summary", "s", "--story", "st", "--description", "d", "--phase", "P1",
               "--acceptance", "a", "--test", "When x, then y", "--areas", "backend").returncode == 0
    doc = _json.loads((k / "tickets.json").read_text())
    doc["tickets"][0]["phase"] = ""
    doc["tickets"][0]["estimate"] = " "
    (k / "tickets.json").write_text(_json.dumps(doc, indent=2))
    r = run("check")
    assert r.returncode == 1
    assert "ACME-001 phase: empty (required)" in r.stderr
    assert "ACME-001 estimate: empty (required)" in r.stderr
    assert "fix:" in r.stderr
